# Underwater Staff

In [1]:
import os
import subprocess

def write_text_file(folder, filename, content):
    """Write content to a text file in the specified folder."""
    file_path = os.path.join(folder, f"{filename}.txt")
    with open(file_path, 'w') as f:
        content = " ".join(map(str, content)) if isinstance(content, list) else str(content)
        f.write(content)

def dng_to_tiff(dng_file, tiff_file):
    """Convert a DNG file to TIFF format using dng_validate.exe."""
    stage = 4
    base_folder = "/Users/barakdiker/Documents/marinetech/underwater_colometry/UW_Colorimetry_Haifa_2025/Lab1/ForMacUsers/"

    # Ensure required settings for linear TIFF conversion
    settings = {
        "wbAndGainSettings": [1, 0, 0, 0],
        "rwSettings": 0,
        "stageSettings": stage,
        "cam_settings": 0,
        "lastStage": stage
    }

    for filename, content in settings.items():
        write_text_file(base_folder, filename, content)

    # Construct the command
    dng_validate_path = os.path.join(base_folder, 'dng_validate.exe')
    cmd = [dng_validate_path, '-16', '-3', tiff_file, dng_file]

    # Execute conversion
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print(f"❌ Error processing {dng_file}:\n{result.stderr}")
    else:
        print(f"✅ Successfully converted {dng_file} → {tiff_file}")


#dng_to_
# Example conversions
dng_path = './barak_florida/GOPR0831.dng'
tiff_path = './barak_florida/GOPR0831.tif'
dng_to_tiff(dng_path, tiff_path)
#dng_to_

✅ Successfully converted ./barak_florida/GOPR0831.dng → ./barak_florida/GOPR0831.tif


# Part 1 

## question 2 

In [18]:
import numpy as np

In [24]:
import tifffile as tiff
image = tiff.imread("/Users/barakdiker/Documents/marinetech/underwater_colometry/UW_Colorimetry_Haifa_2025/Project/barak_florida/Depth_GOPR0831.tif")
print("Image shape:", image.shape)

Image shape: (2924, 3341)


In [25]:
image

array([[0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       ...,
       [0.5215, 0.522 , 0.522 , ..., 0.    , 0.    , 0.    ],
       [0.5215, 0.5215, 0.5215, ..., 0.    , 0.    , 0.    ],
       [0.5215, 0.5215, 0.5215, ..., 0.    , 0.    , 0.    ]],
      dtype=float16)

In [26]:
image[image == 0] = np.nan


In [27]:
image

array([[   nan,    nan,    nan, ...,    nan,    nan,    nan],
       [   nan,    nan,    nan, ...,    nan,    nan,    nan],
       [   nan,    nan,    nan, ...,    nan,    nan,    nan],
       ...,
       [0.5215, 0.522 , 0.522 , ...,    nan,    nan,    nan],
       [0.5215, 0.5215, 0.5215, ...,    nan,    nan,    nan],
       [0.5215, 0.5215, 0.5215, ...,    nan,    nan,    nan]],
      dtype=float16)

In [28]:
tiff.imwrite("./barak_florida/Depth_GOPR0831_new.tif", image)


In [29]:
import tifffile as tiff
image = tiff.imread("/Users/barakdiker/Documents/marinetech/underwater_colometry/UW_Colorimetry_Haifa_2025/Project/barak_eilat/Depth_DSC01590.tif")
print("Image shape:", image.shape)

Image shape: (3648, 5472)


In [30]:
image

array([[0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       ...,
       [0.8125, 0.813 , 0.813 , ..., 0.7827, 0.7827, 0.7827],
       [0.8125, 0.813 , 0.813 , ..., 0.7827, 0.7827, 0.7827],
       [0.8125, 0.813 , 0.813 , ..., 0.7827, 0.7827, 0.7827]],
      dtype=float16)

In [31]:
image[image == 0] = np.nan


In [32]:
image

array([[   nan,    nan,    nan, ...,    nan,    nan,    nan],
       [   nan,    nan,    nan, ...,    nan,    nan,    nan],
       [   nan,    nan,    nan, ...,    nan,    nan,    nan],
       ...,
       [0.8125, 0.813 , 0.813 , ..., 0.7827, 0.7827, 0.7827],
       [0.8125, 0.813 , 0.813 , ..., 0.7827, 0.7827, 0.7827],
       [0.8125, 0.813 , 0.813 , ..., 0.7827, 0.7827, 0.7827]],
      dtype=float16)

In [34]:
tiff.imwrite("./barak_eilat/Depth_DSC01590_new.tif", image)


# Part A 

## downwelling light "E"
Diffuse Downwelling light as "Illuminate D-65"

$ E_0(\lambda) $ - Diffuse downwelling light at the surface 

This is the value E in the code 

In [63]:
import numpy as np
import pandas as pd
E_0 = pd.read_csv("./Data/illuminant-D65.csv",index_col=0)
#E.to_numpy()
#print()
E_0.loc[305]
#for i in E.index:
#    print(i)
E_0 = E_0.loc[(E_0.index%10 == 0)]
E_0 = E_0.loc[400:700]
E_0

intensity
wavelength(nm)           
400               82.7549
410               91.4860
420               93.4318
430               86.6823
440              104.8650
450              117.0080
460              117.8120
470              114.8610
480              115.9230
490              108.8110
500              109.3540
510              107.8020
520              104.7900
530              107.6890
540              104.4050
550              104.0460
560              100.0000
570               96.3342
580               95.7880
590               88.6856
600               90.0062
610               89.5991
620               87.6987
630               83.2886
640               83.6992
650               80.0268
660               80.2146
670               82.2778
680               78.2842
690               69.7213
700               71.6091

## Sensor spectral response 
$ S_c(\lambda) $ - Sensor spectral response 



In [53]:
# Canon_1Ds-Mk-II.csv

S_c = pd.read_csv("./Canon_1Ds-Mk-II.csv",index_col=0)
S_c #df['Column1'] = pd.to_numeric(df['Column1'], downcast='integer', errors='coerce')

red         green      blue
wavelength                                  
400.0       0.001693  4.265969e-03  0.012718
410.0       0.003036  6.123845e-03  0.032369
420.0       0.004576  1.178632e-02  0.077946
430.0       0.002516  2.077617e-02  0.130453
440.0       0.006156  2.726726e-02  0.171201
450.0       0.007412  2.994864e-02  0.203345
460.0       0.007553  4.029466e-02  0.226684
470.0       0.005974  6.700555e-02  0.231991
480.0       0.005344  1.002410e-01  0.220171
490.0       0.005241  1.391980e-01  0.182265
500.0       0.005896  1.877998e-01  0.132878
510.0       0.009689  2.420792e-01  0.083486
520.0       0.016629  2.788448e-01  0.044779
530.0       0.022888  2.920465e-01  0.019306
540.0       0.026349  2.837986e-01  0.012783
550.0       0.031824  2.622650e-01  0.009275
560.0       0.043018  2.293202e-01  0.010195
570.0       0.073507  1.840614e-01  0.009717
580.0       0.120776  1.325640e-01  0.007059
590.0       0.153301  8.548029e-02  0.003737
600.0       0.150329  4.875821e-02  0.000006
610.0       0.138416  2.316997e-02  0.000016
620.0       0.119105  1.247410e-02  0.000008
630.0       0.103533  5.907328e-03  0.000003
640.0       0.085632  1.547049e-03  0.000012
650.0       0.070098  2.423941e-06  0.000008
660.0       0.054293  4.947813e-06  0.000036
670.0       0.037291  7.477073e-06  0.000311
680.0       0.022289  8.575071e-07  0.000119
690.0       0.009166  5.434264e-04  0.000092
700.0       0.005839  2.024399e-04  0.000511

In [64]:
S_c.index = pd.to_numeric(S_c.index, downcast='integer', errors='coerce')

In [65]:
S_c

red         green      blue
wavelength                                  
400         0.001693  4.265969e-03  0.012718
410         0.003036  6.123845e-03  0.032369
420         0.004576  1.178632e-02  0.077946
430         0.002516  2.077617e-02  0.130453
440         0.006156  2.726726e-02  0.171201
450         0.007412  2.994864e-02  0.203345
460         0.007553  4.029466e-02  0.226684
470         0.005974  6.700555e-02  0.231991
480         0.005344  1.002410e-01  0.220171
490         0.005241  1.391980e-01  0.182265
500         0.005896  1.877998e-01  0.132878
510         0.009689  2.420792e-01  0.083486
520         0.016629  2.788448e-01  0.044779
530         0.022888  2.920465e-01  0.019306
540         0.026349  2.837986e-01  0.012783
550         0.031824  2.622650e-01  0.009275
560         0.043018  2.293202e-01  0.010195
570         0.073507  1.840614e-01  0.009717
580         0.120776  1.325640e-01  0.007059
590         0.153301  8.548029e-02  0.003737
600         0.150329  4.875821e-02  0.000006
610         0.138416  2.316997e-02  0.000016
620         0.119105  1.247410e-02  0.000008
630         0.103533  5.907328e-03  0.000003
640         0.085632  1.547049e-03  0.000012
650         0.070098  2.423941e-06  0.000008
660         0.054293  4.947813e-06  0.000036
670         0.037291  7.477073e-06  0.000311
680         0.022289  8.575071e-07  0.000119
690         0.009166  5.434264e-04  0.000092
700         0.005839  2.024399e-04  0.000511

## Part A Section 2.2 question 4 

In [71]:
#np.exp(E_0[400])
np.exp(E_0.loc[400])

intensity    8.709564e+35
Name: 400, dtype: float64

In [ ]:
def simulateBackscatter(l,S_c,rho,E_0,b,c,K_d,z,D):
    return ( b.loc[l] / c.loc[l] * E_0.loc[l]*exp(-K_d.loc[l]*D) * (1- exp(-c.loc[l]*z)) ) * S_c.loc[l]

In [72]:
def simulateDirectSignal(l,S_c,rho,E_0,b,c,K_d,z,D):
    return (rho.loc[l]*E_0.loc[l]*np.exp(-K_d.loc[l] * D)*np.exp(-c.loc[l]*z))* S_c.loc[l]

In [73]:
def simulateImage(l,S_c,rho,E_0,b,c,K_d,z,D):
    return simulateBackscatter(l,S_c,rho,E_0,b,c,K_d,z,D) + simulateDirectSignal(l,S_c,rho,E_0,b,c,K_d,z,D)

## Part A Section 2.2 question 6

Use your function to simulate appearance of the DGK 

In [75]:
# DGKcolorchart_reflectances.csv
rho = pd.read_csv("./Data/DGKcolorchart_reflectances.csv",index_col=0)

In [76]:
rho


Patch1    Patch2    Patch3  ...   Patch16   Patch17   Patch18
wavelength                                ...                              
400         0.333865  0.141195  0.074604  ...  0.000000  0.000000  0.000000
410         0.515463  0.187850  0.134748  ...  0.033810  0.020693  0.003822
420         0.659408  0.207813  0.152440  ...  0.049268  0.030162  0.007026
430         0.707600  0.219641  0.161086  ...  0.071538  0.047802  0.023298
440         0.709417  0.218904  0.154292  ...  0.082913  0.060183  0.042575
450         0.729224  0.241706  0.172267  ...  0.099766  0.059048  0.040251
460         0.733642  0.245332  0.180839  ...  0.094157  0.066578  0.040672
470         0.747980  0.258169  0.185041  ...  0.093462  0.071741  0.047831
480         0.744538  0.259845  0.185339  ...  0.089551  0.077223  0.052154
490         0.749187  0.276416  0.203586  ...  0.085335  0.091557  0.063958
500         0.744275  0.307489  0.233440  ...  0.082761  0.114122  0.080475
510         0.735762  0.319971  0.251092  ...  0.073394  0.126900  0.087188
520         0.722666  0.306861  0.237455  ...  0.067013  0.127186  0.089366
530         0.715986  0.286409  0.221887  ...  0.058551  0.119767  0.081358
540         0.705269  0.261880  0.203526  ...  0.057721  0.115550  0.076345
550         0.699977  0.239722  0.181345  ...  0.051701  0.107547  0.075408
560         0.684949  0.209499  0.156051  ...  0.045482  0.095461  0.063340
570         0.670852  0.184340  0.137572  ...  0.040462  0.084864  0.057489
580         0.671103  0.178563  0.132125  ...  0.043491  0.088033  0.060236
590         0.668333  0.194569  0.146060  ...  0.063894  0.104456  0.068803
600         0.674262  0.221407  0.171500  ...  0.110008  0.134544  0.087553
610         0.676839  0.232187  0.182323  ...  0.142768  0.149358  0.099333
620         0.683235  0.243283  0.190890  ...  0.168232  0.162534  0.102102
630         0.688465  0.249697  0.191905  ...  0.175625  0.160787  0.102279
640         0.707448  0.256454  0.206222  ...  0.189314  0.171246  0.094977
650         0.722896  0.273222  0.221334  ...  0.212323  0.176972  0.100916
660         0.728302  0.282213  0.231542  ...  0.215603  0.180155  0.089577
670         0.749562  0.292883  0.252684  ...  0.233744  0.185661  0.088045
680         0.748609  0.297016  0.242388  ...  0.224807  0.167857  0.057149
690         0.766592  0.292178  0.241834  ...  0.222493  0.163796  0.062334
700         0.797180  0.293260  0.220439  ...  0.211893  0.156334  0.059289

[31 rows x 18 columns]